### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size

### ISSUE THREAD

**Issue by G-virus** [jaewon-lee-b/lte#12]
I am using my manual image datasets with environment.yaml
having modify the train_edsr-baseline-lte.yaml with "root_path" of train_dataset and val_dataset,and change cache "in_memory" to "bin" (bcz of low RAM)
the logger out put is :

train dataset: size=747320
/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/torchvision/transforms/transforms.py:288: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811805959/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  inp: shape=(3, 48, 48)
  coord: shape=(2304, 2)
  cell: shape=(2304, 2)
  gt: shape=(2304, 3)
val dataset: size=1600
  inp: shape=(3, 48, 48)
  coord: shape=(2304, 2)
  cell: shape=(2304, 2)
  gt: shape=(2304, 3)
model: #params=1.7M
Traceback (most recent call last):
  File "/home/qd1205/PycharmProjects/learn_torch/lte/train.py", line 223, in <module>
    main(config, save_path)
  File "/home/qd1205/PycharmProjects/learn_torch/lte/train.py", line 149, in main
    epoch)
  File "/home/qd1205/PycharmProjects/learn_torch/lte/train.py", line 88, in train
    for batch in tqdm(train_loader, leave=False, desc='train'):
  File "/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/qd1205/anaconda3/envs/lte/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 48, 48] at entry 0 and [4, 48, 48] at entry 3

Process finished with exit code 1

**Comment by G-virus** [comment]
the run parameters is:
python train --config configs/train-div2k/train_edsr-baseline-lte.yaml --gpu 1

**Comment by jaewon-lee-b** [comment]
It seems that some images have four channels instead of 3.

**Comment by G-virus** [comment]
> It seems that some images have four channels instead of 3.

thx, I'll try fix it
